services:
  postgres:
    image: postgres:16
    container_name: esdb
    environment:
      POSTGRES_DB: esdb
      POSTGRES_USER: testuser
      POSTGRES_PASSWORD: testpass
    ports:
      - "5432:5432"
    volumes:
      - dbdata:/var/lib/postgresql/dbdata


volumes:
  dbdata: